# Generated by Django 4.2.7 on 2025-10-24 09:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for the webhook', max_length=255)),
                ('url', models.URLField(help_text='Target endpoint URL', max_length=2048, validators=[django.core.validators.URLValidator()])),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers as JSON')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Request body as JSON')),
                ('schedule_type', models.CharField(choices=[('once', 'One-time'), ('recurring', 'Recurring')], max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text="Cron expression for recurring webhooks (e.g., '*/5 * * * *')", max_length=100, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Scheduled datetime for one-time webhooks (UTC)', null=True)),
                ('timezone', models.CharField(default='UTC', help_text="User's timezone", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the webhook is enabled')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum retry attempts on failure')),
                ('retry_delay', models.IntegerField(default=60, help_text='Seconds between retries')),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for one-time webhooks', max_length=255, null=True)),
                ('celery_periodic_task_id', models.IntegerField(blank=True, help_text='ID of PeriodicTask for recurring webhooks', null=True)),
                ('last_execution_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_code', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response content')),
                ('error_message', models.TextField(blank=True, help_text='Error details if failed')),
                ('attempt_number', models.IntegerField(default=1, help_text='Current attempt number')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='webhooks.webhook')),
            ],
            options={
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['webhook', '-executed_at'], name='webhooks_we_webhook_2168e1_idx'), models.Index(fields=['status'], name='webhooks_we_status_940060_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['user', 'is_active'], name='webhooks_we_user_id_51012d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['schedule_type'], name='webhooks_we_schedul_840684_idx'),
        ),
    ]
