# Generated by Django 4.2.7 on 2025-10-27 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Folder name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional folder description')),
                ('color', models.CharField(default='#6366f1', help_text='Hex color code', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name (lucide-react)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent folder for nested organization', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='webhooks.webhookfolder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='webhook',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Optional folder for organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='webhooks.webhookfolder'),
        ),
        migrations.AddIndex(
            model_name='webhookfolder',
            index=models.Index(fields=['user', 'parent'], name='webhooks_we_user_id_6a82a8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='webhookfolder',
            unique_together={('user', 'name', 'parent')},
        ),
    ]
