# Generated by Django 4.2.7 on 2025-10-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_webhookfolder_webhook_folder_and_more'),
    ]

    operations = [
        # Create the Account model
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('ceo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('niche', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('stripe_api_key', models.TextField(blank=True, null=True)),
                ('trainerize_api_key', models.TextField(blank=True, null=True)),
                ('slack_workspace_url', models.CharField(blank=True, max_length=255, null=True)),
                ('slack_api_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('domain_name_main', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('date_joined', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='webhook',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this webhook belongs to (for multi-tenancy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='webhooks.account'),
        ),
        migrations.AddField(
            model_name='webhookfolder',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account this folder belongs to (for multi-tenancy)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_folders', to='webhooks.account'),
        ),
    ]
