# Generated by Django 4.2.7 on 2025-10-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0003_account_webhook_account_webhookfolder_account'),
    ]

    operations = [
        # Slack fields were already removed in a previous fix
        # migrations.RemoveField operations removed to avoid errors
        migrations.AddField(
            model_name='account',
            name='short_url_domain',
            field=models.CharField(blank=True, help_text="Custom domain for short URLs (e.g., 'pay.ao.com')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='trz_admin_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='trz_group_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
