# Generated by Django 4.2.7 on 2025-11-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0004_rename_trainerize_api_key_account_trz_api_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='trainerize_api_key',
            new_name='trz_api_key',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slack_api_account_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='slack_workspace_url',
        ),
    ]
