# Generated by Django 4.2.7 on 2025-10-31 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webhooks', '0004_rename_trainerize_api_key_account_trz_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(db_index=True, help_text="Unique short code (e.g., 'abc123')", max_length=10)),
                ('original_url', models.URLField(help_text='The original long URL to redirect to', max_length=2048)),
                ('domain', models.CharField(db_index=True, help_text="The domain for this short URL (e.g., 'pay.ao.com')", max_length=255)),
                ('title', models.CharField(blank=True, default='', help_text='Optional title/description for the link', max_length=255)),
                ('clicks', models.IntegerField(default=0, help_text='Number of times this URL has been clicked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the link', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this short URL is active')),
                ('account', models.ForeignKey(help_text='Account that owns this short URL', on_delete=django.db.models.deletion.CASCADE, related_name='short_urls', to='webhooks.account')),
            ],
            options={
                'db_table': 'short_urls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referer', models.URLField(blank=True, max_length=2048)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='url_shortener.shorturl')),
            ],
            options={
                'verbose_name_plural': 'Click analytics',
                'db_table': 'click_analytics',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['short_code'], name='short_urls_short_c_01a9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['domain', 'short_code'], name='short_urls_domain_628d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='shorturl',
            index=models.Index(fields=['account', 'created_at'], name='short_urls_account_4ecf26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shorturl',
            unique_together={('domain', 'short_code')},
        ),
        migrations.AddIndex(
            model_name='clickanalytics',
            index=models.Index(fields=['short_url', 'clicked_at'], name='click_analy_short_u_03e63f_idx'),
        ),
        migrations.AddIndex(
            model_name='clickanalytics',
            index=models.Index(fields=['clicked_at'], name='click_analy_clicked_dfb727_idx'),
        ),
    ]
